include ../../Makefile.inc

P=signals/part3/

all:	
	${GCC} sigcom1.c -o sigcom1 ${ECHO}sigcom1.c
	${GCC} sigcom.c -o sigcom ${ECHO}sigcom.c
	${GCC} sigfd1.c -o sigfd1 ${ECHO}sigfd1.c
	${GCC} sigfd.c -o sigfd ${ECHO}sigfd.c
	${GCC} sigtwait2.c -o sigtwait2 ${ECHO}sigtwait2.c
	${GCC} sigtwait3.c -o sigtwait3 ${ECHO}sigtwait3.c
	${GCC} sigtwait.c -o sigtwait ${ECHO}sigtwait.c
	${GCC} sigwait2.c -o sigwait2 ${ECHO}sigwait2.c
	${GCC} sigwait.c -o sigwait ${ECHO}sigwait.c
clean : 
	${RM} *~ pone ptwo sigcom1 sigcom sigfd1 sigfd sigtwait2 sigtwait3 sigtwait sigwait2 sigwait

