include ../../Makefile.inc
P=net/netp8/

all:
	${GCC} cap1.c -o cap1 ${ECHO}cap1.c
	${GCC} cap2.c -o cap2 ${ECHO}cap2.c
	${GCC} cap3.c -o cap3 ${ECHO}cap3.c
	${GCC} cap4.c -o cap4 ${ECHO}cap4.c
	${GCC} cap5.c -o cap5 ${ECHO}cap5.c
clean:
	${RM} cap1 cap2 cap3 cap4 cap5 a.out
