######################################################################
# Automatically generated by qmake (2.01a) Sat May 5 15:07:24 2018
######################################################################

TEMPLATE = app
TARGET = VideoPlayer-0.1
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
FORMS += widget.ui
SOURCES += main.cpp widget.cpp
RESOURCES += images.qrc
