include ../../../Makefile.inc

P=ipc/mqs/part1/

all:	
	${GCC} ftok.c -o ftok ${ECHO}ftok.c
	${GCC} mqinfo.c -o mqinfo ${ECHO}mqinfo.c
	${GCC} msg_file_client.c -o msg_file_client ${ECHO}msg_file_client.c
	${GCC} msg_file_server.c -o msg_file_server ${ECHO}msg_file_server.c
	${GCC} msgls.c -o msgls ${ECHO}msgls.c
	${GCC} msgq1.c -o msgq1 ${ECHO}msgq1.c
	${GCC} msgq21.c -o msgq21 ${ECHO}msgq21.c
	${GCC} msgq22.c -o msgq22 ${ECHO}msgq22.c
	${GCC} msgq23.c -o msgq23 ${ECHO}msgq23.c
	${GCC} msgq3.c -o msgq3 ${ECHO}msgq3.c
	${GCC} qtest1.c -o qtest1 ${ECHO}qtest1.c
	${GCC} qtest.c -o qtest ${ECHO}qtest.c
clean : 
	${RM} ftok mqinfo msg_file_server msg_file_client msgls msgq1 msgq21 msgq22 msgq23 msgq3 qtest1 qtest abc *~

