include ../../Makefile.inc

P=net/netp1/
all:
	${GCC} cli1.c -o cli1  ${ECHO}cli1
	${GCC} cli2.c -o cli2  ${ECHO}cli2
	${GCC} cli3.c -o cli3  ${ECHO}cli3
	${GCC} srv1.c -o srv1  ${ECHO}srv1
	${GCC} srv2.c -o srv2  ${ECHO}srv2
	${GCC} srv3.c -o srv3  ${ECHO}srv3

clean:
	${RM} *~ cli1 cli2 cli3 srv1 srv2 srv3 a.out
