include ../../Makefile.inc

P=signals/part2/

all:	
	${GCC} sigset1.c -o sigset1 ${ECHO}sigset1.c
	${GCC} sigset2.c -o sigset2 ${ECHO}sigset2.c
	${GCC} sigset3.c -o sigset3 ${ECHO}sigset3.c
	${GCC} sigset4.c -o sigset4 ${ECHO}sigset4.c
	${GCC} sigset5.c -o sigset5 ${ECHO}sigset5.c
clean : 
	${RM} *~ sigset1 sigset2 sigset3 sigset4 sigset5

