
DIRS=  netp1   netp11   netp16  netp2_2  netp4  netp6  netp8  		\
	netp10  netp12  netp2   netp3    netp5  netp7  netp9 

all:    
	@ for dir in ${DIRS}; do (cd $${dir}; ${MAKE}) ; done

clean:
	@ for dir in ${DIRS}; do (cd $${dir}; ${MAKE} clean) ; done
