include ../../Makefile.inc
P=net/netp7/

all:
	${GCC} cli1.c -o cli1 ${ECHO}cli1.c
	${GCC} cli3.c -o cli3 ${ECHO}cli3.c
	${GCC} srv1.c -o srv1 ${ECHO}srv1.c
	${GCC} srv2.c -o srv2 ${ECHO}srv2.c
clean:
	${RM} cli1 cli3 srv1 srv2 a.out
