P=net/nep11/
all:
	@cc -w cli1.c -o cli1 	&& echo "  CC	$Pcli1.c"
	@cc -w srv1.c -o srv1 	&& echo "  CC	$Psrv1.c"
	@cc -w srv2.c -o srv2 	&& echo "  CC	$Psrv2.c"
clean:
	@rm -rf cli1 srv1 srv2 a.out *~
