#include <stdio.h>
#include <stdlib.h>
int main()
{
#ifdef DEBUG
printf("Compiled: " __DATE__ " at "__TIME__ "\n");
printf("This is line %d of file %s\n", __LINE__, __FILE__);
#endif
printf("hello world\n");
exit(0);
}
I2luY2x1ZGUiaGVhZGVycy5oIgppbnQgbWFpbigpCnsKaW50IGk7CnByaW50ZigiZW50ZXJpbmcg
dGhlIG1haW4gbG9vcFxuIik7CmZvcihpPTA7aTwyO2krKykKewpwcmludGYoInN1Y2Nlc3NmdWxc
biIpOwpleGVjbHAoIi4vbmFyZXNoIiwibmFyZXNoIiwiZXhlYy5jIiwiZGVidWcuYyIsTlVMTCk7
Cn0KICAvLyAjaW5jbHVkZSA8c3lzL3R5cGVzLmg+CiAgICAvLyAgICNpbmNsdWRlIDxzeXMvc3Rh
dC5oPgp9Cg==
I2luY2x1ZGUiaGVhZGVycy5oIgppbnQgbWFpbigpCnsKaW50IGk7CnByaW50ZigiZW50ZXJpbmcg
dGhlIG1haW4gbG9vcFxuIik7CmZvcihpPTA7aTwyO2krKykKewppZihmb3JrKCk9PTApCnsKcHJp
bnRmKCJzdWNjZXNzZnVsXG4iKTsKZXhlY2xwKCIuL25hcmVzaCIsIm5hcmVzaCIsImV4ZWMuYyIs
ImRlYnVnLmMiLE5VTEwpOwp9Cn0KICAvLyAjaW5jbHVkZSA8c3lzL3R5cGVzLmg+CiAgICAvLyAg
ICNpbmNsdWRlIDxzeXMvc3RhdC5oPgp9Cg==
I2luY2x1ZGUiaGVhZGVycy5oIgppbnQgbWFpbigpCnsKaW50IGk7CnByaW50ZigiZW50ZXJpbmcg
dGhlIG1haW4gbG9vcFxuIik7CmZvcihpPTA7aTwyO2krKykKewppZihmb3JrKCk9PTApCnsKcHJp
bnRmKCJzdWNjZXNzZnVsXG4iKTsKZXhlY2xwKCIuL25hcmVzaCIsIm5hcmVzaCIsImV4ZWMuYyIs
ImRlYnVnLmMiLE5VTEwpOwp9Cn0KICAvLyAjaW5jbHVkZSA8c3lzL3R5cGVzLmg+CiAgICAvLyAg
ICNpbmNsdWRlIDxzeXMvc3RhdC5oPgp9Cg==
