include ../../Makefile.inc

P=net/netp16/
all:
	${GCC} raw.c -o raw ${ECHO}raw.c
	${GCC} rawtcp.c -o rawtcp ${ECHO}rawtcp.c
	${GCC} rawudp.c -o rawudp ${ECHO}rawudp.c
	${GCC} 4.c -o 4 ${ECHO}4.c
clean:
	${RM} 4 raw rawudp rawtcp 	

