include ../../Makefile.inc
P=net/netp5/

all:
	${GCC} hostdet1.c -o hostdet1 ${ECHO}hostdet1.c
	${GCC} hostdet2.c -o hostdet2 ${ECHO}hostdet2.c
	${GCC} hostdet.c -o hostdet ${ECHO}hostdet.c
	${GCC} servdet.c -o servdet ${ECHO}servdet.c
	${GCC} servdet1.c -o servdet1 ${ECHO}servdet1.c
	
clean:
	${RM} hostdet1 hostdet2 hostdet servdet servdet1 a.out
