
include ../../Makefile.inc

P=Desings/desg3/

all:
	${GCC} ui.c viml.c config.c tifhandler.c gifhandler.c jpghandler.c -o App	\
	${ECHO} ui.c viml.c config.c tifhandler.c gifhandler.c jpghandler.c
clean:
	${RM} App
