
include ../../Makefile.inc

P=Designs/desg1/

all:
	${GCC} ui.c gifhandler.c -o gifApp ${ECHO}ui.c giffhandler.c
	${GCC} ui.c tiffhandler.c -o tifApp ${ECHO}ui.c tiffhandler.c

clean:
	${RM} *App .*.swp 
