include ../Makefile.inc

P=clone/

all:	
	${GCC} clone1.c -D_GNU_SOURCE -o clone1 ${ECHO}clone1.c
	${GCC} clone2.c -D_GNU_SOURCE -o clone2 ${ECHO}clone2.c
	${GCC} clone3.c -D_GNU_SOURCE -o clone3 ${ECHO}clone3.c

clean : 
	${RM} clone1 clone2 clone3 

